name: iwoc3-production
on:
  push:
    branches:
      - iwoc3-dev
jobs:
  deploy:
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "${{ secrets.KEY }}" > ssh_key
            chmod 600 ssh_key
            ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
              cd /iwoc3.0
              git pull origin main
              npm install
              npm run build
              pm2 restart all
            EOF