name: IWOC3 CI CD

on:
  push:
    branches: [ "iwoc3-dev" ]

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
                  cd iwoc3.0
                  git pull
                  npm ci
                  pm2 restart iwocBackend
